### ISSUE TITLE
Cannot be used in a pipe

### ISSUE THREAD

**Issue by mwaibel-go** [wgrabowski/ngx-unused#8]
When piping the output to another process, as in
```
$ npx ngx-unused src/tsconfig.json | tee ng-unused.txt
```
node crashes with the following error:

```
/home/mwaibel-go/.npm/_npx/6f3ac8a83e849633/node_modules/ngx-unused/src/common/cli-utils.js:37
    process.stdout.clearLine(-1);
                   ^

TypeError: process.stdout.clearLine is not a function
    at Object.printProgress (/home/mwaibel-go/.npm/_npx/6f3ac8a83e849633/node_modules/ngx-unused/src/common/cli-utils.js:37:20)
    at /home/mwaibel-go/.npm/_npx/6f3ac8a83e849633/node_modules/ngx-unused/src/component/usage.js:9:21
    at Array.reduce (<anonymous>)
    at Object.countComponentUsages (/home/mwaibel-go/.npm/_npx/6f3ac8a83e849633/node_modules/ngx-unused/src/component/usage.js:7:18)
    at Object.countUsages (/home/mwaibel-go/.npm/_npx/6f3ac8a83e849633/node_modules/ngx-unused/src/index.js:16:36)
    at Object.<anonymous> (/home/mwaibel-go/.npm/_npx/6f3ac8a83e849633/node_modules/ngx-unused/cli.js:11:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

I assume the clearLine function is not present when stdout is not a TTY. I suggest not outputting the status information in that case.

Environment:

```
$ uname -a
Linux mwaibel-go-LAPTOP 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
$ node -v
v16.13.0
$ npm -v
8.15.1
```

**Comment by wgrabowski** [comment]
TODO: use `process.stdout.isTTY`
